[package]
name = "rendering_stuff_rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
gl_generator = "0.14"
khronos_api = "3.1.0"

[dependencies]
glfw = "0.60"
ndarray = { version = "0.10", default-features = false}