[package]
name = "rendering_stuff_rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

#[lib]
#crate-type = ["staticlib"]

[build-dependencies]
gl_generator = "0.14"
khronos_api = "3.1.0"

[dependencies]
#gl = "0.14.0"
glfw = "0.60"
ndarray = { version = "0.10", default-features = false}
#ndarray-linalg = "0.17"
#windows = { version = "0.61", features = ["Win32_System_Console"] }

#pkg-config = "0.3"

#[build-dependencies]
#cc = "1.0"
#pkg-config = "0.3"

#[dependencies.glfw]
#version = "0.60"
#default-features = false
