[package]
name = "render_context"
version = "0.8.0"
edition = "2024"


[dependencies]
opengl = {path = "../opengl_abstractions"}
window = {path = "../window"}
matrices = {path = "../matrices"}
shaders = {path = "../shaders"}