#[build]
#target = "x86_64-pc-windows-msvc"


#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "link-args=-Wl,-rpath=..."]
#rustc-link-lib = ["glfw3.dll"]
#rustc-link-search = ["glfw3.dll"]
#rustflags = ["-C", "target-feature=+crt-static"]

#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "target-feature=+crt-static"]