[package]
name = "shaders"
version = "0.8.0"
edition = "2024"


[dependencies]
rust-embed = { version = "8.7.2", default-features = false }

matrices = {path = "../matrices"}
opengl   = {path = "../opengl_abstractions"}
